# This is a basic workflow to help you get started with Actions

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy
      - name: Rust lint
        run: cargo fmt --manifest-path src-tauri/Cargo.toml -- --check
      - name: Rust Clippy
        run: cargo clippy --manifest-path src-tauri/Cargo.toml
      - name: Rust build
        run: cargo build --manifest-path src-tauri/Cargo.toml
      - name: Rust test
        run: cargo test --manifest-path src-tauri/Cargo.toml
      - name: NPM Install dependencies
        run: npm install
      - name: NPM Lint
        run: npm run lint
      - name: NPM Build
        run: npm run build
      - name: Install bundler
        uses: actions-rs/install@v0.1
        with:
          crate: tauri-bundler
      - name: Bundle
        run: npm run tauri build
