# This is a basic workflow to help you get started with Actions

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy, tauri-bundler
      - name: Rust lint
        run: cargo fmt --manifest-path src-tauri/Cargo.toml -- --check
      - name: Rust build
        run: cargo build --manifest-path src-tauri/Cargo.toml
      - name: Rust test
        run: cargo test --manifest-path src-tauri/Cargo.toml
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build

